[package]
name = "bevy_bsn_asset"
version = "0.20.0-dev"
edition = "2024"
description = "Loads `.bsn` scene asset files for Bevy Engine"
homepage = "https://bevy.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
bevy_app = { path = "../bevy_app", version = "0.20.0-dev" }
bevy_asset = { path = "../bevy_asset", version = "0.20.0-dev" }
bevy_bsn = { path = "../bevy_bsn", version = "0.20.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.20.0-dev", features = [
  "bevy_reflect",
] }
bevy_platform = { path = "../bevy_platform", version = "0.20.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.20.0-dev" }
bevy_scene = { path = "../bevy_scene", version = "0.20.0-dev" }

thiserror = { version = "2", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["std"] }

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
